### ISSUE TITLE
Revamp Meta Vault Page 1.2

### ISSUE THREAD

**Issue by toniocodo** [mstable/frontend#120]
![image](https://user-images.githubusercontent.com/13216617/201417074-2db78d00-98b2-47fb-9ade-807d67534f20.png)

- [x] Update background gradient based on primary color vault
- [x] Add Back Button
- [x] Replace vault asset Icon
- [x] Chart color based on primary color vault
