### ISSUE TITLE
Meta Vault UI 1.0

### ISSUE THREAD

**Issue by dimsome** [mstable/frontend#24]
## About

Epic to keep track of the Meta Vault UI development

## User story

As a user, I would want to access Meta Vaults, and deposit/withdraw my assets.

## Related Issues

https://github.com/mstable/mStable-subgraphs-monorepo/issues/34

https://github.com/mstable/mStable-contracts-V2/issues/61

## Subissues

- [x] https://github.com/mstable/frontend/issues/19
- [x] https://github.com/mstable/frontend/issues/26
- [x] https://github.com/mstable/frontend/issues/27
- [x] https://github.com/mstable/frontend/issues/28
- [x] https://github.com/mstable/frontend/issues/29
- [x] https://github.com/mstable/frontend/issues/30
- [x] https://github.com/mstable/frontend/issues/31
- [x] https://github.com/mstable/frontend/issues/32
- [x] https://github.com/mstable/frontend/issues/41
- [x] #56 
- [x] Setup a demo enviroment
- [x] Publish Subgraph & Test
- [x] #62
- [x] #63
