### ISSUE TITLE
Meta Vault Page mobile support

### ISSUE THREAD

**Issue by toniocodo** [mstable/frontend#49]
![image](https://user-images.githubusercontent.com/13216617/201421895-c31de0b0-64e4-4bc9-95e9-a348b4214836.png)

- [x] Sticky bottom navbar with My Position and Operation
- [x] Review padding and cards order
- [x] Full screen modals and dialogs
- [x] Remove outlines from operational widget and yield calc modals
- [x] Create new variants for outline buttons and apply to "History"
- [x] Remove "Expand button" from Vault performance section

Prerequisites

- [x] #71
